Don't cast to atomic_int in test(atomicField)
"load" returns an int anyway, and this was causing a fatal error on
macOS:

CC interrupts-tmp.c
../../../../Macaulay2/d/interrupts.d:25:100: fatal error: used type 'atomic_int' (aka '_Atomic(int)') where arithmetic or pointer type is required
  tmp__5 = (load_Field((*((struct atomic_field*)TS_Get_Local(interrupts_interruptedFlag_id)))) != ((atomic_int)0));
                                                                                                   ^           ~